local modname = core.get_current_modname()
local modpath = core.get_modpath(modname)

dofile(modpath.."/campsite.lua")
dofile(modpath.."/desert_oasis.lua")
dofile(modpath.."/forest_ruins.lua")
dofile(modpath.."/graveyard.lua")
dofile(modpath.."/obelisks.lua")
dofile(modpath.."/spider_cocoon.lua")
dofile(modpath.."/witches_circle.lua")
dofile(modpath.."/statue.lua")
dofile(modpath.."/tree_hideout.lua")
dofile(modpath.."/forest_well.lua")
dofile(modpath.."/forest_grave.lua")
dofile(modpath.."/forest_shelter.lua")
dofile(modpath.."/cave_shelter.lua")
dofile(modpath.."/house_ruin.lua")
dofile(modpath.."/tower.lua")
