--FISHING ROD FUNCTIONS
--Pretty much the entirety of mcl_fishing code would need to be copied over and API-ified in a similar manner to how we handle armor to make new fishing rods easy to register with a wrapper.
