mcl_commands.alias_command("?", "help", false)
mcl_commands.alias_command("pardon", "unban", false)
mcl_commands.rename_command("stop", "shutdown", false)
mcl_commands.alias_command("tell", "msg", false)
mcl_commands.alias_command("w", "msg", false)
mcl_commands.alias_command("tp", "teleport", false)
mcl_commands.rename_command("clear", "clearinv", false)