-- Wielded Item Transformations - http://dev.minetest.net/texture

wieldview.transform = {
	["mcl_core:torch"]="R270",
	["mesecons_torch:mesecon_torch_on"]="R270",
	["mcl_core:sapling"]="R270",
	["mcl_core:junglesapling"]="R270",
	["mcl_core:darksapling"]="R270",
	["mcl_core:acaciasapling"]="R270",
	["mcl_core:birchsapling"]="R270",
	["mcl_core:sprucesapling"]="R270",
	["mcl_core:deadbush"]="R270",
	["mcl_flowers:dandelion"]="R270",
	["mcl_flowers:tulip_orange"]="R270",
	["mcl_flowers:tulip_white"]="R270",
	["mcl_flowers:tulip_pink"]="R270",
	["mcl_flowers:tulip_red"]="R270",
	["mcl_flowers:allium"]="R270",
	["mcl_flowers:azure_bluet"]="R270",
	["mcl_flowers:poppy"]="R270",
	["mcl_flowers:blue_orchid"]="R270",
	["mcl_flowers:oxeye_daisy"]="R270",
	["mcl_flowers:fern"]="R270",
	["mcl_flowers:tallgrass"]="R270",
	["mcl_potions:glass_bottle"]="R270",
	["mcl_potions:water"]="R270",
	["mcl_potions:awkward"]="R270",
	["mcl_potions:thick"]="R270",
	["mcl_potions:mundane"]="R270",

	["screwdriver:screwdriver"]="R270",
	["screwdriver:screwdriver1"]="R270",
	["screwdriver:screwdriver2"]="R270",
	["screwdriver:screwdriver3"]="R270",
	["screwdriver:screwdriver4"]="R270",
}

