mcl_walls.register_wall("mcl_walls:cobble", "Cobblestone Wall", "mcl_core:cobble")
mcl_walls.register_wall("mcl_walls:mossycobble", "Mossy Cobblestone Wall", "mcl_core:mossycobble")
mcl_walls.register_wall("mcl_walls:andesite", "Andesite Wall", "mcl_core:andesite")
mcl_walls.register_wall("mcl_walls:granite", "Granite Wall", "mcl_core:granite")
mcl_walls.register_wall("mcl_walls:diorite", "Diorite Wall", "mcl_core:diorite")
mcl_walls.register_wall("mcl_walls:brick", "Brick Wall", "mcl_core:brick_block")
mcl_walls.register_wall("mcl_walls:sandstone", "Sandstone Wall", "mcl_core:sandstone")
mcl_walls.register_wall("mcl_walls:redsandstone", "Red Sandstone Wall", "mcl_core:redsandstone")
mcl_walls.register_wall("mcl_walls:stonebrick", "Stone Brick Wall", "mcl_core:stonebrick")
mcl_walls.register_wall("mcl_walls:stonebrickmossy", "Mossy Stone Brick Wall", "mcl_core:stonebrickmossy")
mcl_walls.register_wall("mcl_walls:prismarine", "Prismarine Wall", "mcl_ocean:prismarine")
mcl_walls.register_wall("mcl_walls:endbricks", "End Stone Brick Wall", "mcl_end:end_bricks")
mcl_walls.register_wall("mcl_walls:netherbrick", "Nether Brick Wall", "mcl_nether:nether_brick")
mcl_walls.register_wall("mcl_walls:rednetherbrick", "Red Nether Brick Wall", "mcl_nether:red_nether_brick")
