mcl_walls.register_wall("mcl_walls:cobble", "Cobblestone Wall", "mcl_core:cobble", {"default_cobble.png"})
mcl_walls.register_wall("mcl_walls:mossycobble", "Mossy Cobblestone Wall", "mcl_core:mossycobble", {"default_mossycobble.png"})
mcl_walls.register_wall("mcl_walls:andesite", "Andesite Wall", "mcl_core:andesite", {"mcl_core_andesite.png"})
mcl_walls.register_wall("mcl_walls:granite", "Granite Wall", "mcl_core:granite", {"mcl_core_granite.png"})
mcl_walls.register_wall("mcl_walls:diorite", "Diorite Wall", "mcl_core:diorite", {"mcl_core_diorite.png"})
mcl_walls.register_wall("mcl_walls:brick", "Brick Wall", "mcl_core:brick_block", {"default_brick.png"})
mcl_walls.register_wall("mcl_walls:sandstone", "Sandstone Wall", "mcl_core:sandstone", {"mcl_core_sandstone_top.png", "mcl_core_sandstone_bottom.png", "mcl_core_sandstone_normal.png"})
mcl_walls.register_wall("mcl_walls:redsandstone", "Red Sandstone Wall", "mcl_core:redsandstone", {"mcl_core_red_sandstone_top.png", "mcl_core_red_sandstone_bottom.png", "mcl_core_red_sandstone_normal.png"})
mcl_walls.register_wall("mcl_walls:stonebrick", "Stone Brick Wall", "mcl_core:stonebrick", {"default_stone_brick.png"})
mcl_walls.register_wall("mcl_walls:stonebrickmossy", "Mossy Stone Brick Wall", "mcl_core:stonebrickmossy", {"mcl_core_stonebrick_mossy.png"})
mcl_walls.register_wall("mcl_walls:prismarine", "Prismarine Wall", "mcl_ocean:prismarine", {{name="mcl_ocean_prismarine_anim.png", animation={type="vertical_frames", aspect_w=32, aspect_h=32, length=45.0}}})
mcl_walls.register_wall("mcl_walls:endbricks", "End Stone Brick Wall", "mcl_end:end_bricks", {"mcl_end_end_bricks.png"})
mcl_walls.register_wall("mcl_walls:netherbrick", "Nether Brick Wall", "mcl_nether:nether_brick", {"mcl_nether_nether_brick.png"})
mcl_walls.register_wall("mcl_walls:rednetherbrick", "Red Nether Brick Wall", "mcl_nether:red_nether_brick", {"mcl_nether_red_nether_brick.png"})
