--SHIELD FUNCTIONS
--Pretty much the entirety of mcl_shields code would need to be copied over and API-ified in a similar manner to how we handle armor to make registering new shields easy with a wrapper.
