# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: docker-24

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      
      - name: Install vltest CLI
        shell: bash
        run: id=$(docker create --pull always git.minetest.land/voxelibre/voxelibre-test/vltest:master) && docker cp "$id:/vltest" ./vltest && docker rm "$id"

      - name: Inspect workspace mounts
        shell: bash
        run: |
          pwd
          ls -l game.conf
          docker inspect "$HOSTNAME" \
            --format '{{json .Mounts}}'
      
      - name: Lint
        shell: bash
        run: ./vltest lint
      
      - name: Server startup test
        shell: bash
        run: ./vltest server unittests
