on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: teknomunk/luanti-ci
    steps:
      - name: Checkout Source
        run: |
          mkdir VoxeLibre
          cd VoxeLibre
          git init .
          git remote add origin https://git.minetest.land/VoxeLibre/VoxeLibre.git
          git fetch --depth=1 origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - name: Server Startup
        run: sh tests/server-startup.sh
        env:
          FORGEJO_TOKEN: override
          GITHUB_TOKEN: override
      - name: Unit Tests
        run: sh tests/unit-tests.sh
        env:
          FORGEJO_TOKEN: override
          GITHUB_TOKEN: override
      - name: Luacheck
        run: sh tests/luacheck/test.sh
        env:
          FORGEJO_TOKEN: override
          GITHUB_TOKEN: override
      - name: Lua Language Server Checks
        run: sh tests/lua-language-server.sh
        env:
          FORGEJO_TOKEN: override
          GITHUB_TOKEN: override
