on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: teknomunk/luanti-ci
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Unit Tests
        run: sh tests/unit-tests.sh
      - name: Luacheck
        run: sh tests/luacheck/test.sh
      - name: Lua Language Server Checks
        run: sh tests/lua-language-server.sh
      - name: Server Startup
        run: sh tests/server-startup.sh
