mobs:register_mob("mobs:creeper", {
	type = "monster",
	hp_max = 10,
	collisionbox = {-0.2, 0, -0.2, 0.2, 1.4, 0.2},
	visual = "mesh",
	mesh = "creatures_creeper.x",
	textures = {"mobs_creeper.png"},
	--visual_size = {x = 1.1, y = 1.1},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 1.3,
	randomsound= "creeper_random",
	run_velocity = 1.1,
	on_rightclick = nil,
	jump = 0,
	damage = 0,
	drops = {
		{name = "default:gunpowder",
		chance = 1,
		min = 0,
		max = 2,},
	},
	armor = 70,
	drawtype = "front",
	lava_damage = 15,
	light_damage = 0,
	attack_type = "kamicaze",
})

