mobs:register_mob("mobs:herobrine", {
	type = "monster",
	hp_max = 120,
	collisionbox = {-0.4, -1.3, -0.4, 0.4, 1, 0.4},
	visual = "mesh",
	mesh = "creatures_herobrine.x",
	textures = {"mobs_herobrine.png"},
	makes_footstep_sound = true,
	view_range = 10,
	walk_velocity = 4.8,
	run_velocity = 5.1,
	on_rightclick = nil,
		drops = {
		{name = "mobs:rotten_flesh",
		chance = 1,
		min = 1,
		max = 3,},
	},
	jump = 0,
	damage = 9999,
	armor = 100,
	drawtype = "front",
	lava_damage = 0,
	light_damage = 0,
	attack_type = "dogfight",
	animation = {
		speed_normal = 10,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		die_start = 162,
		die_end = 166,
	},
})

