mobs:register_mob("mobs:spider", {
	type = "monster",
	hp_max = 16,
	--collisionbox = {-0.4, -1.0, -0.4, 0.4, 0.8, 0.4},
	collisionbox = {-0.9, -0.01, -0.7, 0.7, 0.6, 0.7},
	visual_size = {x=7,y=7},
	visual = "mesh",
	mesh = "creatures_spider.x",
	textures = {"mobs_spider.png"},
	--visual_size = {x = 1.1, y = 1.1},
	makes_footstep_sound = true,
	view_range = 20,
	walk_velocity = 1,
	run_velocity = 4,
	hostile_type = 2,
	on_rightclick = nil,
	jump = false,
	damage = 2,
	drops = {
		{name = "farming:string",
		chance = 2,
		min = 1,
		max = 3,},
		{name = "mobs:spider_eye",
		chance = 30,
		min = 1,
		max = 1,},
	},
	armor = 200,
	light_resistant = true,
	drawtype = "front",
	water_damage = 0,
	lava_damage = 15,
	light_damage = 0,
	step = 1,
	attack_type = "dogfight",
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 1,
		stand_end = 1,
		walk_start = 20,
		walk_end = 40,
		run_start = 20,
		run_end = 40,
		punch_start = 50,
		punch_end = 90,
	},
})
