mobs:register_mob("mobs:zombie", {
	type = "monster",
	hp_max = 20,
	--collisionbox = {-0.4, -1.0, -0.4, 0.4, 0.8, 0.4},
	collisionbox = {-0.4, -1.3, -0.4, 0.4, 1, 0.4},
	visual = "mesh",
	mesh = "creatures_zombie.x",
	textures = {"mobs_zombie.png"},
	--visual_size = {x = 1.1, y = 1.1},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 0.8,
	randomsound= "zombie_random",
	run_velocity = 1.1,
	on_rightclick = nil,
	damage = 1,
	drops = {
		{name = "mobs:rotten_flesh",
		chance = 2,
		min = 1,
		max = 2,},
		{name = "default:sword_steel",
		chance = 15,
		min = 0,
		max = 1,},
		{name = "default:shovel_gold",
		chance = 18,
		min = 0,
		max = 1,},
		{name = "default:steel_ingot",
		chance = 24,
		min = 1,
		max = 5,},
		{name = "farming:carrot_item",
		chance = 10,
		min = 0,
		max = 1,},
		{name = "farming:potato_item",
		chance = 25,
		min = 0,
		max = 1,},
	},
	armor = 100,
	drawtype = "front",
	lava_damage = 15,
	light_damage = 5,
	attack_type = "dogfight",
	animation = {
		speed_normal = 10,
		speed_run = 30,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		die_start = 162,
		die_end = 166,
	},
})
