-- SETTINGS
BLINKY_PLANT_INTERVAL = 3
NEW_STYLE_WIRES  = true  -- true = new nodebox wires, false = old raillike wires
PRESSURE_PLATE_INTERVAL = 0.04
OBJECT_DETECTOR_RADIUS = 6
PISTON_MAXIMUM_PUSH = 11 -- +1
MOVESTONE_MAXIMUM_PUSH = 0
