on: [push]
jobs:
  test:
    runs-on: voxelibre-ci
    container:
      image: 127.0.0.1:5000/voxelibre-test:latest
    steps:
      - name: Checkout
        run: cd /VoxeLibre && git fetch --depth=1 origin ${{ github.sha }} && git checkout ${{ github.sha }} && rm -Rvf /VoxeLibre/./tests/docker/luanti/games/devtest
      - name: Unit Tests
        run: cd /VoxeLibre; sh tests/unit-tests.sh
      - name: Luacheck
        run: cd /VoxeLibre; sh tests/luacheck/test.sh
      - name: Server Startup
        run: cd /VoxeLibre; sh tests/server-startup.sh
      - name: Lua Language Server Checks
        run: cd /VoxeLibre; sh tests/lua-language-server.sh
