---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by michieal.
--- DateTime: 12/14/22 10:14 PM
---


local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)
local bamboo = "mcl_bamboo:bamboo"

local function tiki_lamp()
	if minetest.get_modpath("mcl_lanterns") then
		if mcl_lanterns ~= nil then
			mcl_lanterns.register_lantern("tikilamp", {
				description = S("Tiki Lamp"),
				longdesc = S("Tiki Lamps are light sources which can be placed on the top or the bottom of most blocks."),
				texture = "mcl_bamboo_extras_tikilamp.png",
				texture_inv = "mcl_bamboo_extras_tikilamp_inv.png",
				light_level = 14,
			})

			minetest.register_craft({
				output = "mcl_lanterns:tikilamp_floor",
				recipe = {
					{bamboo, bamboo,bamboo},
					{bamboo, "mcl_torches:torch", bamboo},
					{bamboo, bamboo,bamboo},
				},
			})
		end
	end
end





-- ------------------------------------
tiki_lamp()