---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Michieal.
--- DateTime: 5/11/25 7:13 PM
---

minetest.register_craft({
	output = "vl_deepslate_tools:pick_deepslate",
	recipe = {
		{"mcl_deepslate:deepslate", "mcl_deepslate:deepslate", "mcl_deepslate:deepslate"},
		{"", "mcl_core:stick", ""},
		{"", "mcl_core:stick", ""},
	}
})

minetest.register_craft({
	output = "vl_deepslate_tools:shovel_deepslate",
	recipe = {
		{"mcl_deepslate:deepslate"},
		{"mcl_core:stick"},
		{"mcl_core:stick"},
	}
})

minetest.register_craft({
	output = "vl_deepslate_tools:sword_deepslate",
	recipe = {
		{"mcl_deepslate:deepslate"},
		{"mcl_deepslate:deepslate"},
		{"mcl_core:stick"},
	}
})

minetest.register_craft({
	output = "vl_deepslate_tools:axe_deepslate",
	recipe = {
		{"mcl_deepslate:deepslate", "mcl_deepslate:deepslate"},
		{"mcl_deepslate:deepslate", "mcl_core:stick"},
		{"", "mcl_core:stick"},
	}
})
minetest.register_craft({
	output = "vl_deepslate_tools:axe_deepslate",
	recipe = {
		{"mcl_deepslate:deepslate", "mcl_deepslate:deepslate"},
		{"mcl_core:stick", "mcl_deepslate:deepslate"},
		{"mcl_core:stick", ""},
	}
})

minetest.register_craft({
	output = "vl_deepslate_tools:hoe_deepslate",
	recipe = {
		{"mcl_deepslate:deepslate", "mcl_deepslate:deepslate"},
		{"", "mcl_core:stick"},
		{"", "mcl_core:stick"}
	}
})
minetest.register_craft({
	output = "vl_deepslate_tools:hoe_deepslate",
	recipe = {
		{"mcl_deepslate:deepslate", "mcl_deepslate:deepslate"},
		{"mcl_core:stick", ""},
		{"mcl_core:stick", ""}
	}
})

-- Hammer & spear crafting recipies
local materials = {
	deepslate = "mcl_deepslate:deepslate",
}

local s = "mcl_core:stick"
local b = ""
for t,m in pairs(materials) do
	core.register_craft({
		output = "vl_deepslate_tools:hammer_"..t,
		recipe = {
			{ m, b, m },
			{ m, s, m },
			{ b, s, b },
		}
	})
	core.register_craft({
		output = "vl_deepslate_tools:spear_"..t,
		recipe = {
			{ m, b, b },
			{ b, s, b },
			{ b, b, s },
		}
	})
	core.register_craft({
		output = "vl_deepslate_tools:spear_"..t,
		recipe = {
			{ b, b, m },
			{ b, s, b },
			{ s, b, b },
		}
	})
end
