---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Michieal.
--- DateTime: 5/11/25 7:13 PM
---
local modname = core.get_current_modname()
local modpath = core.get_modpath(modname)
local S = core.get_translator(modname)
--
-- Tool definition
--

--[[
dig_speed_class group:
- 1: Painfully slow
- 2: Very slow
- 3: Slow
- 4: Fast
- 5: Very fast
- 6: Extremely fast
- 7: Instantaneous
]]


local sword_longdesc = S("Swords are great in melee combat, as they are fast, deal high damage and can endure countless battles. Swords can also be used to cut down a few particular blocks, such as cobwebs.")
-- local sword_use = S("To slash multiple enemies, hold the sword in your hand, then use (rightclick) an enemy.")
-- TODO slash attack not implemented yet

local spear_tt = S("Reaches farther") .. "\n" .. S("Can be thrown")
local spear_longdesc = S("Spears are great in melee combat, as they have an increased reach. They can also be thrown.")
local spear_use = S("To throw a spear, hold it in your hand, then hold use (rightclick) in the air.")

local wield_scale = mcl_vars.tool_wield_scale

---- variable values... (partial list.)
local deepslate = {
	uses = 150,
	speed = 4.25,
	level = 3,
	hammerspeed = 2.25,
	spearspeed = 2,
	spearlevel = 1,
	stone = 150
}

local SPEAR_RANGE = 4.5

local function spear_on_place(itemstack, user, pointed_thing)
	if pointed_thing.type == "node" then
		-- Call on_rightclick if the pointed node defines it
		local node = core.get_node(pointed_thing.under)
		if user and not user:get_player_control().sneak then
			if core.registered_nodes[node.name] and core.registered_nodes[node.name].on_rightclick then
				return core.registered_nodes[node.name].on_rightclick(pointed_thing.under, node, user, itemstack) or itemstack
			end
		end
	end

	itemstack:get_meta():set_int("active", 1)
	return itemstack
end

-- include crafting recipes
dofile(modpath .. "/crafting.lua")

-- Register tools.

vl_tools.pickaxe.register("vl_deepslate_tools:pick_deepslate", {
	description = S("Deepslate Pickaxe"),
	icon = "vl_deepslate_tools_deepslatepick.png",
	repair_material = "mcl_deepslate:deepslate_cobbled",

	groups = { dig_speed_class = 3, enchantability = 5 },

	tool_capabilities = {
		full_punch_interval = 0.83333333,
		max_drop_level = 3,
		damage_groups = { fleshy = 3 },
		punch_attack_uses = 66,
	},

	_mcl_diggroups = {
		pickaxey = { speed = deepslate.speed, level = deepslate.level, uses = deepslate.uses },
	},

	overrides = { vl_max_ench_lvl = 2 },
	no_craft = true,
})

vl_tools.shovel.register("vl_deepslate_tools:shovel_deepslate", {
	description = S("Deepslate Shovel"),
	icon = "vl_deepslate_tools_deepslateshovel.png",
	repair_material = "mcl_deepslate:deepslate_cobbled",

	groups = { dig_speed_class = 3, enchantability = 5 },

	tool_capabilities = {
		full_punch_interval = 1,
		max_drop_level = 3,
		damage_groups = { fleshy = 3 },
		punch_attack_uses = 66,
	},

	_mcl_diggroups = {
		shovely = { speed = deepslate.speed, level = deepslate.level, uses = deepslate.uses },
	},

	overrides = { vl_max_ench_lvl = 2 },
	no_craft = true,
})

vl_tools.hoe.register("vl_deepslate_tools:hoe_deepslate", {
	description = S("Deepslate Hoe"),
	icon = "vl_deepslate_tools_deepslatehoe.png",
	repair_material = "mcl_deepslate:deepslate_cobbled",

	groups = { enchantability = 5 },

	tool_capabilities = {
		full_punch_interval = 0.5,
		damage_groups = { fleshy = 1 },
		punch_attack_uses = deepslate.stone,
	},

	_mcl_diggroups = {
		hoey = { speed = deepslate.speed, level = deepslate.level, uses = deepslate.uses },
	},

	overrides = { vl_max_ench_lvl = 2 },
})


vl_tools.axe.register("vl_deepslate_tools:axe_deepslate", {
	description = S("Deepslate Axe"),
	icon = "vl_deepslate_tools_deepslateaxe.png",
	repair_material = "mcl_deepslate:deepslate_cobbled",

	groups = { dig_speed_class = 3, enchantability = 5 },

	tool_capabilities = {
		full_punch_interval = 1.25,
		max_drop_level = 3,
		damage_groups = { fleshy = 9 },
		punch_attack_uses = 66,
	},

	_mcl_diggroups = {
		axey = { speed = deepslate.speed, level = deepslate.level, uses = deepslate.uses },
	},

	overrides = { vl_max_ench_lvl = 2 },
	no_craft = true,
})

------------------ weapons

core.register_tool("vl_deepslate_tools:sword_deepslate", {
	description = S("Deepslate Sword"),
	_doc_items_longdesc = sword_longdesc,
	inventory_image = "vl_deepslate_tools_deepslatesword.png",
	wield_scale = wield_scale,
	groups = { weapon = 1, sword = 1, dig_speed_class = 3, enchantability = 5 },
	tool_capabilities = {
		full_punch_interval = 0.625,
		max_drop_level = 3,
		damage_groups = { fleshy = 5 },
		punch_attack_uses = 132,
	},
	sound = { breaks = "default_tool_breaks" },
	_repair_material = "mcl_deepslate:deepslate_cobbled",
	_mcl_toollike_wield = true,
	_mcl_diggroups = {
		swordy = { speed = deepslate.speed, level = deepslate.level, uses = deepslate.uses },
		swordy_cobweb = { speed = deepslate.speed, level = deepslate.level, uses = deepslate.uses }
	},
	vl_max_ench_lvl = 2,
})

vl_tools.hammer.register("vl_deepslate_tools:hammer_deepslate", {
	description = S("Deepslate Hammer"),
	icon = "vl_deepslate_tools_deepslatehammer.png",
	repair_material = "mcl_deepslate:deepslate_cobbled",

	groups = { dig_speed_class = 2, enchantability = 5 },

	tool_capabilities = {
		full_punch_interval = 1.3,
		max_drop_level = 3,
		damage_groups = { fleshy = 5.25 },
		punch_attack_uses = deepslate.uses,
	},

	_mcl_diggroups = {
		pickaxey = { speed = deepslate.hammerspeed, level = deepslate.level, uses = deepslate.uses },
		shovely = { speed = deepslate.hammerspeed, level = deepslate.level, uses = deepslate.uses },
	},

	overrides = { vl_max_ench_lvl = 2 },
	no_craft = true,
})

core.register_tool("vl_deepslate_tools:spear_deepslate", {
	description = S("Deepslate Spear"),
	_tt_help = spear_tt,
	_doc_items_longdesc = spear_longdesc,
	_doc_items_usagehelp = spear_use,
	inventory_image = "vl_deepslate_tools_deepslatespear.png",
	wield_scale = wield_scale,
	on_place = spear_on_place,
	on_secondary_use = spear_on_place,
	groups = { weapon = 1, weapon_ranged = 1, spear = 1, dig_speed_class = 2, enchantability = 5 },
	range = SPEAR_RANGE,
	tool_capabilities = {
		full_punch_interval = 0.75,
		max_drop_level = 3,
		damage_groups = { fleshy = 4.25 },
		punch_attack_uses = deepslate.uses,
	},
	sound = { breaks = "default_tool_breaks" },
	_repair_material = "mcl_deepslate:deepslate_cobbled",
	_mcl_toollike_wield = true,
	_mcl_diggroups = {
		swordy = { speed = deepslate.spearspeed, level = deepslate.spearlevel, uses = deepslate.uses },
		swordy_cobweb = { speed = deepslate.spearspeed, level = deepslate.spearlevel, uses = deepslate.uses }
	},
	touch_interaction = "short_dig_long_place",
	_mcl_spear_thrown_damage = 6,
	vl_max_ench_lvl = 2,
})


local pr = PcgRandom(1234)
core.register_on_craft(function(itemstack, player, old_craft_grid, craft_inv)
	if string.sub(itemstack:get_name(), 1, 18) ~= "vl_deepslate_tools"
			or mcl_enchanting.is_enchanted(itemstack:get_name())
			or math.random(1, 2) == 1 then
		return
	end
	local enchantment = mcl_enchanting.get_random_enchantment(itemstack, false, true, {}, pr)
	mcl_enchanting.enchant(itemstack, enchantment, 1)
	tt.reload_itemstack_description(itemstack)
end)
