local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
	{S("Creator of MineClone"), 0x0A9400, {
		"davedevils",
	}},
	{S("Creator of VoxeLibre"), 0xFBF837, {
		"Wuzzy",
	}},
	{S("Maintainer"), 0xFFFFFF, {
		"Herowl",
	}},
	{S("Previous Maintainers"), 0xFFFFFF, {
		"Fleckenstein",
		"kay27",
		"cora",
		"Nicu",
		"AncientMariner",
	}},
	{S("Developers"), 0xF84355, {
		"AFCMS",
		"epCode",
		"TomCon / SmokeyDope",
		"Faerraven / Michieal",
		"teknomunk",
		"AncientMariner",
	}},
	{S("Past Developers"), 0xF84355, {
		"jordan4ibanez",
		"ryvnf",
		"iliekprogrammar",
		"kabou",
		"MysticTempest",
		"NO11",
		"SumianVoice",
		"PrairieWind",
		"FossFanatic",
		"Codiac",
		"chmodsayshello",
		"MrRar",
		"rudzik8",
		"kno10",
	}},
	{S("Contributors"), 0x52FF00, {
		"RandomLegoBrick",
		"Code-Sploit",
		"aligator",
		"Rootyjr",
		"bzoss",
		"talamh",
		"Laurent Rocher",
		"HimbeerserverDE",
		"TechDudie",
		"Alexander Minges",
		"ArTee3",
		"ZeDique la Ruleta",
		"pitchum",
		"wuniversales",
		"Bu-Gee",
		"David McMackins II",
		"Nicholas Niro",
		"Wouters Dorian",
		"Blue Blancmange",
		"Jared Moody",
		"Li0n",
		"Midgard",
		"Saku Laesvuori",
		"Yukitty",
		"ZedekThePD",
		"aldum",
		"dBeans",
		"nickolas360",
		"yutyo",
		"Tianyang Zhang",
		"j45",
		"Marcin Serwin",
		"erle",
		"E",
		"n_to",
		"debiankaios",
		"Gustavo6046 / wallabra",
		"CableGuy67",
		"Benjamin Schötz",
		"Doloment",
		"Sydney Gems",
		"Emily2255",
		"Emojigit",
		"FinishedFragment",
		"sfan5",
		"Blue Blancmange",
		"Jared Moody",
		"SmallJoker",
		"Sven792",
		"aldum",
		"Dieter44",
		"Pepebotella",
		"Lazerbeak12345",
		"mrminer",
		"Thunder1035",
		"opfromthestart",
		"snowyu",
		"FaceDeer",
		"Herbert West",
		"GuyLiner",
		"3raven",
		"anarquimico",
		"TheOnlyJoeEnderman",
		"Ranko Saotome",
		"Gregor Parzefall",
		"Wbjitscool",
		"b3nderman",
		"CyberMango",
		"gldrk",
		"atomdmac",
		"emptyshore",
		"FlamingRCCars",
		"uqers",
		"Niterux",
		"appgurueu",
		"seventeenthShulker",
		"DinoNuggies4665",
		"basxto",
		"Morik666",
		"Eliy21",
		"mdk",
		"Alessandra Lozoya",
		"VanicGame",
		"ThePython10110",
		"Araca",
		"Montandalar",
		"mim",
		"Dark",
		"Bakawun",
		"JoseDouglas26",
		"Zasco",
		"PrWalterB",
		"michaljmalinowski",
		"nixnoxus",
		"Potiron",
		"Tuxilio",
		"Impulse",
		"Doods",
		"SOS-Games",
		"Bram",
		"qoheniac",
		"WillConker",
		"0ldude",
		"tacotexmex",
		"Pixel-Peter",
		"OgelGames",
		"blitzdoughnuts",
		"goodspeed",
		"Bloodaxe",
		"ClementMR",
		"THE-NERD2",
		"ethan",
		"villager8472",
		"ninjum",
		"OpenSauce04",
		"grillo-delmal",
		"Yoric",
		"potatoalienof13",
		"HalfShadow111",
		"cyberonkel",
		"oku",
		"fancyfinn9",
		"Chiragon",
		"Archie",
		"newrizen",
		"wrrrzr",
		"antimundo",
		"farfind",
	}},
	{S("Music"), 0xA60014, {
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"Dark Reaven Music (https://soundcloud.com/dark-reaven-music) for the main menu theme (Calmed Cube) and Traitor (horizonchris96), which is licensed under https://creativecommons.org/licenses/by-sa/3.0/",
		"Jester for helping to finely tune VoxeLibre (https://www.youtube.com/@Jester-8-bit). Songs: Hailing Forest, Gift, 0dd BL0ck, Flock of One (License CC BY-SA 4.0)",
		"Exhale & Tim Unwin for some wonderful VoxeLibre tracks (https://www.youtube.com/channel/UClFo_JDWoG4NGrPQY0JPD_g). Songs: Valley of Ghosts, Lonely Blossom, Farmer (License CC BY-SA 4.0)",
		"Diminixed for 3 fantastic tracks and remastering and leveling volumes. Songs: Afternoon Lullaby (pianowtune02), Spooled (ambientwip02), Never Grow Up (License CC BY-SA 4.0)",
	}},
	{S("Original Mod Authors"), 0x343434, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"debian044 / debian44",
		"chmodsayshello",
		"cora",
		"Faerraven / Michieal",
		"PrairieWind",
		"ChrisPHP",
		"rudzik8",
	}},
	{S("3D Models"), 0x0019FF, {
		"22i",
		"tobyplowy",
		"epCode",
		"Faerraven / Michieal",
		"SumianVoice",
		"thunder1035",
		"Herowl",
		"Chiragon",
	}},
	{S("Textures"), 0xFF9705, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Faerraven / Michieal",
		"Nicu",
		"Exhale",
		"Aeonix_Aeon",
		"Wbjitscool",
		"SmokeyDope",
		"thunder1035",
		"Herowl",
		"NovaWostra",
		"rudzik8",
		"kno10",
		"Chiragon",
	}},
	{S("Translations"), 0x00FF60, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"SakuraRiu",
		"anarquimico",
		"syl",
		"Temak",
		"megustanlosfrijoles",
		"kbundg",
		"Isaac Dennis",
		"ADLON",
		"Sab Pyrope",
		"JoseDouglas26",
		"0ldude",
		"Bloodaxe",
		"ethan",
		"Herowl",
		"kno10",
		"Pixel-Peter",
		"Laudrin",
		"chmodsayshello",
		"ninjum",
		"HalfShadow111",
		"newrizen",
		"antimundo",
	}},
	{S("Funders"), 0xF7FF00, {
		"40W",
		"bauknecht",
		"Cora",
	}},
	{S("Special thanks"), 0x00E9FF, {
		"The Luanti team for making and supporting an engine, and distribution infrastructure that makes this all possible",
		"The workaholics who spent way too much time writing for the Minecraft Wiki. It's an invaluable resource for creating this game",
		"Notch and Jeb for being the major forces behind Minecraft",
	}},
}
