local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
	{S("Creator of MineClone"), 0x0A9400, {
		"davedevils",
	}},
	{S("Creator of MineClone2"), 0xFBF837, {
		"Wuzzy",
	}},
	{S("Maintainers"), 0xFF51D5, {
		"AncientMariner",
		"Nicu",
	}},
	{S("Previous Maintainers"), 0xFFFFFF, {
		"Fleckenstein",
		"jordan4ibanez",
		"cora",
	}},
	{S("Developers"), 0xF84355, {
		"bzoss",
		"AFCMS",
		"epCode",
		"ryvnf",
		"iliekprogrammar",
		"MysticTempest",
		"Rootyjr",
		"aligator",
		"Code-Sploit",
		"NO11",
		"kabou",
		"rudzik8",
		"chmodsayshello",
		"PrairieWind",
		"RandomLegoBrick",
		"SumianVoice",
		"MrRar",
		"talamh",
		"Faerraven / Michieal",
		"FossFanatic ",
		"SmokeyDope",
	}},
	{S("Contributors"), 0x52FF00, {
		"Laurent Rocher",
		"HimbeerserverDE",
		"TechDudie",
		"Alexander Minges",
		"ArTee3",
		"ZeDique la Ruleta",
		"pitchum",
		"wuniversales",
		"Bu-Gee",
		"David McMackins II",
		"Nicholas Niro",
		"Wouters Dorian",
		"Blue Blancmange",
		"Jared Moody",
		"Li0n",
		"Midgard",
		"Saku Laesvuori",
		"Yukitty",
		"ZedekThePD",
		"aldum",
		"dBeans",
		"nickolas360",
		"yutyo",
		"Tianyang Zhang",
		"j45",
		"Marcin Serwin",
		"erlehmann",
		"E",
		"Benjamin Schötz",
		"Doloment",
		"Sydney Gems",
		"Emily2255",
		"Emojigit",
		"FinishedFragment",
		"sfan5",
		"Blue Blancmange",
		"Jared Moody",
		"SmallJoker",
		"Sven792",
		"aldum",
		"Dieter44",
		"Pepebotella",
		"Lazerbeak12345",
		"mrminer",
		"Thunder1035",
		"opfromthestart",
		"snowyu",
		"FaceDeer",
		"Herbert West",
		"GuyLiner",
		"3raven",
		"anarquimico",
		"TheOnlyJoeEnderman",
		"Ranko Saotome",
		"Gregor Parzefall",
		"Wbjitscool",
		"b3nderman",
		"CyberMango",
		"gldrk",
		"atomdmac",
		"emptyshore",
	}},
	{S("MineClone5"), 0xA60014, {
		"kay27",
		"Debiankaios",
		"epCode",
		"NO11",
		"j45",
		"chmodsayshello",
		"3raven",
		"PrairieWind",
		"Gustavo6046 / wallabra",
		"CableGuy67",
		"MrRar",
	}},
	{S("Mineclonia"), 0xFFFFFF, {
		"erlehmann",
		"Li0n",
		"E",
		"n_to",
	}},
	{S("Original Mod Authors"), 0x343434, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
		"cora",
		"Faerraven / Michieal",
	}},
	{S("3D Models"), 0x0019FF, {
		"22i",
		"tobyplowy",
		"epCode",
		"Faerraven / Michieal",
	}},
	{S("Textures"), 0xFF9705, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
		"MysticTempest",
		"RandomLegoBrick",
		"cora",
		"Faerraven / Michieal",
		"Nicu",
	}},
	{S("Translations"), 0x00FF60, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
		"Pepebotella",
		"Emojigit",
		"snowyu",
		"3raven",
		"SakuraRiu",
		"anarquimico",
		"syl",
	}},
	{S("Funders"), 0xF7FF00, {
		"40W",
		"bauknecht",
		"Cora",
	}},
	{S("Special thanks"), 0x00E9FF, {
		"celeron55 for creating Minetest",
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"wsor for working tirelessly in the shadows for the good of all of us, particularly helping with solving contentDB and copyright issues.",
		"The workaholics who spent way too much time writing for the Minecraft Wiki. It's an invaluable resource for creating this game",
		"Notch and Jeb for being the major forces behind Minecraft",
		"Dark Reaven Music (https://soundcloud.com/dark-reaven-music) for the main menu theme (Calmed Cube) and Traitor (horizonchris96), which is licensed under https://creativecommons.org/licenses/by-sa/3.0/",
		"Jester for helping to finely tune MineClone2 (https://www.youtube.com/@Jester-8-bit). Songs: Hailing Forest, Gift, 0dd BL0ck, Flock of One (License CC BY-SA 4.0)",
		"Exhale & Tim Unwin for some wonderful MineClone2 tracks (https://www.youtube.com/channel/UClFo_JDWoG4NGrPQY0JPD_g). Songs: Valley of Ghosts, Lonely Blossom, Farmer (License CC BY-SA 4.0)",
		"Diminixed for 3 fantastic tracks and remastering and leveling volumes. Songs: Afternoon Lullaby (pianowtune02), Spooled (ambientwip02), Never Grow Up (License CC BY-SA 4.0)",
	}},
}
