local modname = minetest.get_current_modname()
local S = minetest.get_translator(modname)

return {
	{S("Creator of MineClone"), 0x0A9400, {
		"davedevils",
	}},
	{S("Creator of MineClone2"), 0xFBF837, {
		"Wuzzy",
	}},
	{S("Maintainers"), 0xFF51D5, {
		"Nicu",
		"cora",
	}},
	{S("Previous Maintainers"), 0xFFFFFF, {
		"Fleckenstein",
		"jordan4ibanez",
	}},
	{S("Developers"), 0xF84355, {
		"bzoss",
		"AFCMS",
		"epCode",
		"ryvnf",
		"iliekprogrammar",
		"MysticTempest",
		"Rootyjr",
		"aligator",
		"Code-Sploit",
		"NO11",
		"kabou",
	}},
	{S("Contributors"), 0x52FF00, {
		"Laurent Rocher",
		"HimbeerserverDE",
		"TechDudie",
		"Alexander Minges",
		"ArTee3",
		"ZeDique la Ruleta",
		"pitchum",
		"wuniversales",
		"Bu-Gee",
		"David McMackins II",
		"Nicholas Niro",
		"Wouters Dorian",
		"Blue Blancmange",
		"Jared Moody",
		"Li0n",
		"Midgard",
		"Saku Laesvuori",
		"Yukitty",
		"ZedekThePD",
		"aldum",
		"dBeans",
		"nickolas360",
		"yutyo",
		"Tianyang Zhang",
		"j45",
		"Marcin Serwin",
		"erlehmann",
		"E",
		"Benjamin Schötz",
		"Doloment",
		"Sydney Gems",
		"talamh",
		"Emily2255",
		"Emojigit",
		"FinishedFragment",
		"sfan5",
		"Blue Blancmange",
		"Jared Moody",
		"SmallJoker",
		"Sven792",
		"aldum",
		"Dieter44",
	}},
	{S("MineClone5"), 0xA60014, {
		"kay27",
		"Debiankaios",
		"epCode",
		"NO11",
		"j45",
		"3raven",
		"PrarieWind",
		"Gustavo1",
		"CableGuy67",
	}},
	{S("Mineclonia"), 0xFFFFFF, {
		"erlehmann",
		"Li0n",
		"E",
		"n_to",
	}},
	{S("Original Mod Authors"), 0x343434, {
		"Wuzzy",
		"Fleckenstein",
		"BlockMen",
		"TenPlus1",
		"PilzAdam",
		"ryvnf",
		"stujones11",
		"Arcelmi",
		"celeron55",
		"maikerumine",
		"GunshipPenguin",
		"Qwertymine3",
		"Rochambeau",
		"rubenwardy",
		"stu",
		"4aiman",
		"Kahrl",
		"Krock",
		"UgnilJoZ",
		"lordfingle",
		"22i",
		"bzoss",
		"kilbith",
		"xeranas",
		"kddekadenz",
		"sofar",
		"4Evergreen4",
		"jordan4ibanez",
		"paramat",
	}},
	{S("3D Models"), 0x0019FF, {
		"22i",
		"tobyplowy",
		"epCode",
	}},
	{S("Textures"), 0xFF9705, {
		"XSSheep",
		"Wuzzy",
		"kingoscargames",
		"leorockway",
		"xMrVizzy",
		"yutyo",
		"NO11",
		"kay27",
	}},
	{S("Translations"), 0x00FF60, {
		"Wuzzy",
		"Rocher Laurent",
		"wuniversales",
		"kay27",
		"pitchum",
		"todoporlalibertad",
		"Marcin Serwin",
	}},
	{S("Funders"), 0xF7FF00, {
		"40W",
	}},
	{S("Special thanks"), 0x00E9FF, {
		"celeron55 for creating Minetest",
		"Jordach for the jukebox music compilation from Big Freaking Dig",
		"The workaholics who spent way too much time writing for the Minecraft Wiki. It's an invaluable resource for creating this game",
		"Notch and Jeb for being the major forces behind Minecraft",
	}},
}
