---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by michieal.
--- DateTime: 11/19/22 7:13 AM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by michieal.
--- DateTime: 10/23/22 4:50 AM
---
-- LOCALIZATION

local S = minetest.get_translator("mcl_hamburger")

local modname = minetest.get_current_modname()
local modpath = minetest.get_modpath(modname)

local table = table
local DEBUG = false

local enable_burger = minetest.settings:get_bool("mcl_enable_hamburger",true)
local use_alt = minetest.settings:get_bool("mcl_hamburger_alt_texture",false)

mcl_hamburger = {}

-- call to register your hamburger.
function mcl_hamburger.register_burger_craft(cooked_meat)
	minetest.register_craft({
		type = "fuel",
		recipe = "mcl_hamburger:hamburger",
		burntime = 2,
	})

	minetest.register_craft({
		output = "mcl_hamburger:hamburger",
		recipe = {
			{ "mcl_farming:bread"},
			{ cooked_meat }, -- "mcl_mobitems:cooked_beef" for a reg hamburger. Grind up clowns for a Big Mac.
			{ "mcl_farming:bread" },
		},
	})
end

local hamburger_def = {
	description = S("A Hamburger"),
	_doc_items_longdesc = S("A tasty hamburger that is sure to lure villagers around like a lead. Can be eaten."),
	_doc_items_usagehelp = S("wield this item to pull villagers to you."),
	_tt_help = S("A tasty hamburger that is sure to lure villagers. 'I'll gladly pay you Tuesday, for a hamburger today.' - Wimpy."),
	inventory_image = "mcl_hamburger.png",
	wield_image = "mcl_hamburger.png",
	on_place = minetest.item_eat(8),
	on_secondary_use = minetest.item_eat(8),
	groups = { food = 2, eatable = 8 },
	_mcl_saturation = 13.8,
}

if not enable_burger then
	hamburger_def.groups.not_in_creative_inventory = 1
end

if use_alt == false then
	minetest.register_craftitem("mcl_hamburger:hamburger", hamburger_def)
else
	local hamburger_alt = table.copy(hamburger_def)
	hamburger_alt.inventory_image = "mcl_hamburger_alt.png"
	hamburger_alt.wield_image = "mcl_hamburger_alt.png"
	minetest.register_craftitem("mcl_hamburger:hamburger", hamburger_alt)
end

local function register_achievements()

	awards.register_achievement("mcl_hamburger:hamburger", {
		title = S("Burger Time!"),
		description = S("Craft a Hamburger."),
		icon = "mcl_hamburger.png",
		trigger = {
			type = "craft",
			item = "mcl_hamburger:hamburger",
			target = 1
		},
		type = "Advancement",
		group = "Overworld",
	})

end

if enable_burger then
	-- make the villagers follow the item
	minetest.registered_entities["mobs_mc:villager"].nofollow = false
	-- add it to the follow items.
	table.insert(minetest.registered_entities["mobs_mc:villager"].follow,"mcl_hamburger:hamburger")
	-- register the item and crafting recipe.
	mcl_hamburger.register_burger_craft("mcl_mobitems:cooked_beef")
	-- add in the super cool achievement(s)!
	register_achievements()
end

